version: '2'
services:
  development:
    build: .
    command: npm start -- --host 0.0.0.0
    ports:
      - "8080:8080"
    volumes:
      - .:/app/
      - /app/node_modules
  production:
    build: .
    ports:
      - "80:80"
